### ISSUE TITLE
Save does not function

### ISSUE THREAD

**Issue by mcsapp** [adrian17/Gallifreyan#8]
The Save button only opens up a blank Tab in both Chrome and Edge.

**Comment by adrian17** [comment]
Should be fixed now (with 2f805f3e99e7d26c939e054995ec008fdb9b1846). Tested on FF and Chrome, not on Edge.

**Comment by adrian17** [comment]
And sorry for a late response.

**Comment by mcsapp** [comment]
No problem at all I actually just saw this anyway.  I've confirmed that it
works for me.
